### ISSUE TITLE
Invalid certificate authority when trying to post https requests to firebase

### ISSUE THREAD

**Issue by euph00** [euph00/Orbital-team-5243#14]
When on singapore based networks, there seems to be an issue with connecting to and retrieving data from firebase. Problem was discovered morning of 22 july. All attempts to access data in firebase storage, be it through the scribex app or a web browser logged into the project console with an admin account is met with NET::ERR_CERT_AUTHORITY_INVALID. Problem appears to be resolved when accessing the data through a vpn from foreign location. Please advise.

NET::ERR_CERT_AUTHORITY_INVALID
Subject: SN-SINTP1-A0401.singnet.com.sg

Issuer: SN-SINTP1-A0401.singnet.com.sg

Expires on: May 10, 2023

Current date: Jul 22, 2022

**Comment by euph00** [comment]
Firebase has posted an error that traffic from Singapore is being interrupted. No error on our part for code. Awaiting google to resolve server issues.

**Comment by nyanyui** [comment]
Issue has been resolved, the app are able to access files from firebase storage now
